##//for the connection with mysql
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/olympus_riviera?useSSL-false
#    username: root
#    password: 1234
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api?ssl=false
    username: postgres
    password: olympus_riviera
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect