## For the connection with MySQL (commented out)
## spring:
##   datasource:
##     url: jdbc:mysql://localhost:3306/olympus_riviera?useSSL=false
##     username: root
##     password: 1234
#
#spring:
#  datasource:
#    # PostgreSQL Configuration
#    url: jdbc:postgresql://localhost:5432/olympus_riviera?ssl=false
#    username: postgres
#    password: olympus_riviera
#    # For remote PostgreSQL (commented out)
#    # url: jdbc:postgresql://ep-divine-violet-a21u7316.eu-central-1.aws.neon.tech/olympus_riviera?user=olympus_riviera_owner&password=wHa8KvuZNf7e&sslmode=require
#    # url: jdbc:postgresql://195.251.210.147:8881/postgres?ssl=false
#    # username: admin
#    # password: 9GKSM9wD356VfQ6
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  logging:
#    level:
#      org.springframework.security: DEBUG
#
#  application:
#    security:
#      jwt:
#        secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
#        access-token-expiration: 86400000
#        refresh-token-expiration: 604800000
