##//for the connection with mysql
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/olympus_riviera?useSSL-false
#    username: root
#    password: 1234
spring:
  datasource:
    url: jdbc:postgresql://localhost:8080/olympus_riviera?useSSL-false
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
